export const editorialCopy = {
  'zh-CN': {
    related: '相关原话',
    all: '全部原话',
    seeAll: '查看全部转写',
    relatedOnly: '返回相关原话',
    peek: '需要核对时，回到原话',
    checking: '正在核对',
    details: '发言详情',
    feedback: '反馈理解',
    feedbackPrompt: '请重新核对下面这段原话与当前理解的对应关系。我认为需要调整的是：',
    newContent: '有新的会议内容，当前阅读位置已保留。',
    apply: '查看新内容',
    missing: '所引用的原话版本暂不可用。',
    latest: '回到最新',
    more: '会议操作',
    exploreHint: '基于当前讨论，探索其他可能',
    original: '原话',
  },
  en: {
    related: 'Related words',
    all: 'Original words',
    seeAll: 'View full transcript',
    relatedOnly: 'Back to related words',
    peek: 'Return to the original words when you need to check.',
    checking: 'Checking',
    details: 'Source details',
    feedback: 'Review understanding',
    feedbackPrompt:
      'Please review how these original words relate to the current understanding. What I would change:',
    newContent: 'New meeting content is available. Your reading position is preserved.',
    apply: 'View updates',
    missing: 'The cited source revision is not available.',
    latest: 'Back to latest',
    more: 'Meeting actions',
    exploreHint: 'Explore other possibilities from this discussion',
    original: 'Original words',
  },
};
